@startuml data-flow
scale 3
skinparam dpi 300
skinparam classAttributeIconSize 0
skinparam backgroundColor transparent
skinparam classFontSize 14
skinparam classAttributeFontSize 13
skinparam class {
  BackgroundColor white
  BorderColor #cccccc
  AttributeFontColor #000000
  Padding 4
}
skinparam note {
  BackgroundColor #f5f5f5
  BorderColor #cccccc
  FontColor #333333
}


enum "data-flow" {
  übergreifend
  1 Planung
  2 Erhebung und Aufbereitung
  3 Management
  4 Analyse
  5 Publikation und Nachnutzung
  nicht anwendbar
}

note bottom of "data-flow"
  Datenflussstufe, der eine
  Kompetenz zugeordnet ist.
  
  Zeigt die Stufe im Datenzyklus an,
  die ein Lernziel behandelt.
  
  Englisch:
  cross-cutting / 1 Planning /
  2 Collection and Preparation /
  3 Management / 4 Analysis /
  5 Publication and Reuse / not applicable
end note

@enduml
